[package]
name = "flash-script"
version = "0.1.0"
authors = ["why8ther <lturtsamuel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
lazy_static = "1.4"
log = "0.4.8"
env_logger = "0.6.2"
regex = "1.3.9"