[package]
name = "hyper-scripter-util"
version = "0.3.2"
authors = ["why8ther <lturtsamuel@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4"

[dev-dependencies]
env_logger = "0.6.2"
log = "0.4.8"