[package]
name = "hyper-scripter-util"
version = "0.1.0"
authors = ["why8ther <lturtsamuel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"